@startuml

cloud "filtered-stream"<<Twitter>>

queue tweets<<Kafka>>
queue correlations<<Kafka>>

component "tweet-consume-publisher"<<Quarkus>>
component "spark-processor"<<Spark>>
component "analytics-indicator"<<Vaadin>>

[filtered-stream] -(0-> [tweet-consume-publisher]
[tweet-consume-publisher] -right-> [tweets]

[tweets] -right-> [spark-processor]
[spark-processor] -right-> [correlations]

[correlations] --> [analytics-indicator]

@enduml